export const SET_MARKER = 'SET_MARKER';
export const SET_REGION = 'SET_REGION';
export const SEARCH_MAP = 'SEARCH_MAP';
export const SET_SELECTED_PICKUP = 'SET_SELECTED_PICKUP';
export const SET_SELECTED_DESTINATION = 'SET_SELECTED_DESTINATION';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_MAP_TYPE = 'SET_MAP_TYPE';
